### ISSUE TITLE
Strange indexing with lists and negative indices

### ISSUE THREAD

**Issue by jl-wynen** [scipp/scipp#3102]
Indexing with a list containing negative indices doesn't work and produces strange errors.

Given 
```python
import scipp as sc
v=sc.array(dims=['x'],values=[1,2,3])
```

I get
```python
>>> v[-1]
<scipp.Variable> ()      int64  [dimensionless]  3

>>> v[[-1]]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
scipp._scipp.core.DimensionError: Dimension size cannot be negative.

>>> v[[-1, 2]]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
scipp._scipp.core.DimensionError: Dimension size cannot be negative.

>>> v[[-1, 2, 1]]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
IndexError: Bin indices out of range

>>> v[[-1, 2, 1, 2]]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
IndexError: Bin indices out of range

>>> v[[1, 2, -1]]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
IndexError: Bin begin index must be less or equal to its end index.
```

Notice the different errors. Scipp seems to be doing something different depending on the position of the negative index.

**Comment by jokasimr** [comment]
Seems this has been fixed. 

![Image](https://github.com/scipp/scipp/assets/20954731/2bc2de45-f131-4f3b-8c01-2ce5355822a8)

**Comment by jokasimr** [comment]
I did a bisection and the first error was last encountered in commit 6356f6caa92.

**Comment by jl-wynen** [comment]
Great! Thanks for checking!
