### ISSUE TITLE
Plotting libraries are a hard requirement when it should not be

### ISSUE THREAD

**Issue by DanNixon** [scipp/scipp#893]
Matplotlib:
```
>>> import scipp
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dan/miniconda3/envs/test/lib/python3.7/scipp/__init__.py", line 14, in <module>
    from . import neutron
  File "/home/dan/miniconda3/envs/test/lib/python3.7/scipp/neutron/__init__.py", line 10, in <module>
    from .instrument_view import instrument_view
  File "/home/dan/miniconda3/envs/test/lib/python3.7/scipp/neutron/instrument_view.py", line 7, in <module>
    from ..plot.render import render_plot
  File "/home/dan/miniconda3/envs/test/lib/python3.7/scipp/plot/render.py", line 5, in <module>
    import matplotlib
ModuleNotFoundError: No module named 'matplotlib'
```

ipywidegts:
```
>>> import scipp
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dan/miniconda3/envs/test/lib/python3.7/scipp/__init__.py", line 14, in <module>
    from . import neutron
  File "/home/dan/miniconda3/envs/test/lib/python3.7/scipp/neutron/__init__.py", line 10, in <module>
    from .instrument_view import instrument_view
  File "/home/dan/miniconda3/envs/test/lib/python3.7/scipp/neutron/instrument_view.py", line 7, in <module>
    from ..plot.render import render_plot
  File "/home/dan/miniconda3/envs/test/lib/python3.7/scipp/plot/render.py", line 6, in <module>
    import ipywidgets as ipw
ModuleNotFoundError: No module named 'ipywidgets'
```

**Comment by nvaytet** [comment]
This is related to the instrument view. Unless it is urgent, and I'll address this at the same time as #869
